name: Publish Documentation

on: [push]

jobs:
  build:
    name: Build storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Cache Storybook
        id: cache-storybook
        uses: actions/cache@v2
        with:
          path: storybook-static/
          key: ${{ runner.os }}-${{ hashFiles('src/components') }}
      - name: Build storybook docs
        if: steps.cache-storybook.outputs.cache-hit != 'true'
        run: npm run build-storybook
      - name: Upload built docs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: storybook-docs
          path: storybook-static/
  publish:
    name: Publish to Github Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Download docs artifacts
        uses: actions/download-artifact@v2
        with:
          name: storybook-docs
          path: docs/
      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/
